<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset="UTF-8" />
  <title>RaudoCMS | Administración</title>
  <?php Tag::css('bootstrap') ?>
  <?php //Tag::css('style') ?>
  <?php echo Html::includeCss() ?>
</head>
<body>
    <div class="topbar" data-scrollspy="scrollspy"><div class="topbar-inner">
    <div class="container-fluid"><?php echo Html::link('admin/', 'RaudoCMS','class="brand" title="RaudoCMS | Administración"') ?>
        <ul class="nav">
                <li><?php echo Html::link('admin/paginas/','Páginas') ?></li>
                <li class="dropdown" data-dropdown="dropdown">
			<a class="dropdown-toggle" href="#">Status</a>
			<ul class="dropdown-menu">
				<li><?php echo Html::link('admin/status/','Info') ?></li>
				<li><?php echo Html::link('admin/status/test','Test bt') ?></li>
				<li class="divider"></li>
				<li><?php echo Html::link('admin/status/agradecimientos','Agradecimientos') ?></li>
			</ul>
		</li>
                <li><?php echo Html::link('admin/usuarios/','Usuarios') ?></li>
                <li><a href="admin/usuarios/salir">Salir usuario foto</a></li>
        </ul>
    </div>
    </div></div>
    <div class='container'>
        <?php View::content() ?>

        <?php //View::partial('kumbia/footer') ?>
    <p>© 2012 RaudoCMS</p>
    <p><?php echo 'Tiempo: '.round((microtime(1)-START_TIME),4).' seg.'; echo ', Memoria Usada: '.number_format(memory_get_usage() / 1048576, 2).' MB' ?></p>
    </div>
<script src="http://code.jquery.com/jquery-1.7.min.js"></script>
<?php echo Tag::js('bootstrap-dropdown');
echo Tag::js('bootstrap-twipsy');
echo Tag::js('bootstrap-alerts') ?>
</body>
</html>
