<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset="UTF-8" />
  <title>RaudoCMS | Administración</title>
  <?php Tag::css('bootstrap') ?>
  <?php //Tag::css('style') ?>
  <?php echo Html::includeCss() ?>
</head>
<body>
    <div class="topbar" data-scrollspy="scrollspy"><div class="topbar-inner">
    <div class="container-fluid"><a class="brand" href="#" title="RaudoCMS Administración">RaudoCMS</a>
        <ul class="nav">
                <li><a href="">Ir a web</a></li>
                <li><a href="">xxxx</a></li>
                <li><a href="">zzzz</a></li>
                <li><a href="admin/usuarios/salir">Salir usuario foto</a></li>
        </ul>
    </div>
    </div></div>
    <div class='container'>
        <?php View::content(); ?>

        <?php //View::partial('kumbia/footer') ?>
    <p>© 2012 RaudoCMS</p>
    <p><?php echo 'Tiempo: '.round((microtime(1)-START_TIME),4).' seg.'; echo ', Memoria Usada: '.number_format(memory_get_usage() / 1048576, 2).' MB';?></p>
    </div>
</body>
</html>
