<!DOCTYPE html>
<html lang="es">
    <head>
        <base href="/RaudoCMS/" />
        <meta charset="<?php echo APP_CHARSET ?>" />
        <title>RaudoCMS</title>
        <?php Tag::css( 'cms' ) ?>
        <?php echo Html::includeCss() ?>
 		<?php echo Tag::js( 'jquery/jquery.min' ); ?>
  		<?php echo Tag::js( 'wymeditor/jquery.wymeditor' ); ?>
    </head>
    <body>
        <header>
            <h1>RaudoCMS | Administración</h1>
            <hr />
        </header>
        <?php View::content(); ?></div>
        <footer>
            <p>© RaudoCMS 2011</p>
        </footer>
    </body>
</html>
<?php #_::e( $_SESSION ); ?>