<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="<?php echo APP_CHARSET ?>" />
        <title>RaudoCMS</title>
        <?php Tag::css( 'cms' ) ?>
        <?php echo Html::includeCss() ?>
 		<?php echo Tag::js( 'jquery/jquery.min' ); ?>
  		<?php echo Tag::js( 'wymeditor/jquery.wymeditor' ); ?>
    </head>
    <body>
        <header>
            <h1>RaudoCMS | Administración</h1>
            <hr />
        </header>
        <aside>
            <h3>Páginas:</h3>
            <?php View::partial( 'admin/paginas', false, get_object_vars( $controller ) ); ?>
            <hr />
        </aside>
        <section>
            <h3>Página:</h3>
            <div id="pagina"></div>
            <hr />
        </section>
        <footer>
            <p>© RaudoCMS 2011</p>
        </footer>
    </body>
</html>
<?php #_::e( $_SESSION ); ?>