<div id="info">
";

    /**
     * Verificando permisos del dir temp/
     */
    if(!is_writable(APP_PATH.'temp')){
        $tmp = "Debes darle permiso a: '".basename(APP_PATH)."/temp/'";
    } else {
        $tmp = 'Directorio temp... ok';
    }

    /**
     * Configuracion del config.ini
     */
    $config = Config::read('config');

    $databases = ($config['application']['database']) ? 'On' : 'Off';
    $status = ($config['application']['production']) ? 'Production' : 'Development';

    if(isset($config['application']['locale'])){
        $locale = $config['application']['locale'];
    } else {
        $locale = 'No se ha especificado un locale';
    }
    if(isset($config['application']['timezone'])){
        $timezone = $config['application']['timezone'];
    } else {
        $timezone = 'No se ha especificado un Timezone en el config.ini. Pero el servidor tiene <strong>'.date_default_timezone_get().'</strong>';
    }
    if(isset($config['application']['cache_driver'])){
        $cahe_driver = $config['application']['cache_driver'];
    } else {
        $cache_driver = 'No ha seleccionado un driver para la cache';
    }

?&gt;
        <h2>config.ini <span class="app"> de </span></h2>

        <div id="conf">
        <h4>Directorio temp/:</h4>
        

        <h4>Estado Actual del Framework: </h4>
        <p>Ver <a href="http://wiki.kumbiaphp.com/KumbiaPHP_Framework_Versi%C3%B3n_1.0_Spirit#Modos_de_una_Aplicaci.C3.B3n">Modos de ejecución</a></p>

        <h4>Carga Automática de Modelos: </h4>
        <p>Habilita la carga de modelos automática.</p>

        <h4>Base de Datos: </h4>
        <p>Datos de la conexión a la BD que será utilizada, ver configuración <a href="http://wiki.kumbiaphp.com/KumbiaPHP_Framework_Versi%C3%B3n_1.0_Spirit#databases.ini">databases.ini</a>.</p>

        <h4>Carga de Modelos:</h4>
        <p>Ver <a href="http://wiki.kumbiaphp.com/KumbiaPHP_Framework_Versi%C3%B3n_1.0_Spirit#Carga_selectiva_de_modelos">Carga Selectiva de Modelos</a>.</p>

        <h4>Charset: </h4>
        <p>Codificación de caracteres. Recomendado UTF-8</p>

        <h4>TimeZone: </h4>
        <p>Zona horaria que usará el Framework.</p>

        <h4>Cache Driver: </h4>
        <p>Driver que se utilizara para realizar las operaciones de cache.</p>

        <h4>Locale: </h4>
        <p>Localización. Característica que depende de los locale instalado en el servidor.</p>
        </div>
</div>
