<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset="UTF-8" />
  <title>RaudoCMS</title>
  <?php Tag::css('bienvenida') ?>
  <?php Tag::css('style') ?>
  <?php echo Html::includeCss() ?>
</head>
<body>
    <div id='content'>
        <div id='head'>
            <h1 id='logo'>RaudoCMS</h1>

            <div class='alignright'>
                <p id='config'>
                    <span class='app'><?php echo basename(dirname(APP_PATH)) ?></span>
                    <?php echo Html::link('kumbia/status', 'Config', 'title="Ver configuración de la aplicación"') ?>
                </p>
             </div>
        </div>

        <?php View::content(); ?>

        <?php View::partial('kumbia/footer') ?>
    </div>
</body>
</html>
