
<style>
body
{
	overflow: hidden;
}

#editor
{ 
	margin: 0;
	position: realtive;
	top: 0;
	bottom: 0;
	left: 0;
	right: 0;
}
</style>

<pre id="editor"><?php echo $codigo; ?></pre>

<?php echo Tag::js( 'src/ace' ); ?>
<?php echo Tag::js( 'src/theme-twilight' ); ?>
<?php echo Tag::js( 'src/mode-php' ); ?>
<script>
window.onload = function() {
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/twilight");
    
    var JavaScriptMode = require("ace/mode/php").Mode;
    editor.getSession().setMode(new JavaScriptMode());
};
</script>
