
<form action="/admin/pagina" method="post">
	<textarea class="wymeditor" name="codigo"><?php echo $codigo; ?></textarea>
	<select name="accion">
		<option value="editar">Editar</option>
		<option value="borrar">Borrar</option>
	</select>
	<input name="pagina" value="<?php echo $pagina; ?>" type="hidden">
	<button class="wymupdate type="submit">Enviar</button>
	<button class="codigo" type="button">Codigo</button>
</form>

<script type="text/javascript">
$( 'button.codigo' ).on( 'click', function()
{
	var dir = $( 'input[name="pagina"]' ).val();
	location = '/admin/cms/codigo?dir='+dir;
});
$( '.wymeditor' ).wymeditor();
</script>
