<h1>Agradecimientos<h1>

<h2>KumbiaPHP Framework</h2>
<p>RaudoCMS no hubiera sido posible sin <a href="http://www.kumbiaphp.com/">KumbiaPHP</a></p>
<p>Licencia: new BSD</p>

<h2>Bootstrap de Twitter</h2>
<p>Gracias a los desarrolladore de Twitter por liberar el <a href="http://twitter.github.com/bootstrap/">bootstrap de twitter</a></p>
<p>Nos ha facilitado mucho la creación de la zona administrativa</p>
<p>Licencia: apache2</p>

<h2>CodeMirror</h2>
<p>Un magnífico editor de código <a href="http://codemirror.net/">CodeMirror</a></p>
<p>Licencia: MIT</p>
