<h1>Test del bootstrap de Twitter</h1>
<h2>Mensajes Flash:: (igual que siempre)</h2>
<?php
Flash::valid('<strong>RaudoCMS</strong> va perfecto !');
Flash::error('<strong>Error</strong> en xxx');
Flash::warning('<strong>Alerta:</strong> en su config.');
Flash::info('<strong>RaudoCMS</strong> tu próximo CMS');
?>
<h2>Etiquetas BT::label('texto','tipo-opcional')</h2>
<?php

?>
<h2>Próximamente más</h2>
